spring:
  application:
    name: ms-asistencias
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8083

logging:
  level:
    root: info

jwt:
  secret: ${JWT_SECRET:tu-clave-muy-segura-de-32-caracteres-o-mas-1234}
